# Generated by Django 3.2.4 on 2021-06-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userImage',
            field=models.ImageField(default='./static/frontend/svg/user.svg', upload_to='userImage/'),
        ),
    ]
